function AddTextEntry(Key, Value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), Key, Value)
end

Citizen.CreateThread(function()
	AddTextEntry('POL_C0', '0')
	AddTextEntry('POL_C1', '1')
	AddTextEntry('POL_C2', '2')
	AddTextEntry('POL_C3', '3')
	AddTextEntry('POL_C4', '4')
	AddTextEntry('POL_C5', '5')
	AddTextEntry('POL_C6', '6')
	AddTextEntry('POL_C7', '7')
	AddTextEntry('POL_C8', '8')
	AddTextEntry('POL_C9', '9')

	AddTextEntry('POL_C0_DEP','0 - Patrol')
	AddTextEntry('POL_C1_DEP','1 - SCU')
	AddTextEntry('POL_C2_DEP','2 - HVTU')
	AddTextEntry('POL_C3_DEP','3 - Park Rangers')
	AddTextEntry('POL_C4_DEP','4 - S.W.A.T.')
	AddTextEntry('POL_C5_DEP','5 - SRU')
	AddTextEntry('POL_C6_DEP','6 - BTF')
	AddTextEntry('POL_C7_DEP','7')
	AddTextEntry('POL_C8_DEP','8')
	AddTextEntry('POL_C9_DEP','9')

	AddTextEntry('POL_C0_RANK','0 - Cadet')
	AddTextEntry('POL_C1_RANK','1 - Solo Cadet')
	AddTextEntry('POL_C2_RANK','2 - Officer / Deputy')
	AddTextEntry('POL_C3_RANK','3 - Sr Officer / Deputy')
	AddTextEntry('POL_C4_RANK','4 - Corporal')
	AddTextEntry('POL_C5_RANK','5 - Sergeant')
	AddTextEntry('POL_C6_RANK','6 - Lieutenant')
	AddTextEntry('POL_C7_RANK','7 - Captain')
	AddTextEntry('POL_C8_RANK','8 - Ass. Chief / Undersheriff ')
	AddTextEntry('POL_C9_RANK','9 - Chief of Police / Sheriff')

	AddTextEntry('pol_LIV1', 'Los Santos Police Department')
	AddTextEntry('pol_LIV2', 'Los Santos Police Department - K9')
	AddTextEntry('pol_LIV3', 'Blaine County Sheriffs Office')
	AddTextEntry('pol_LIV4', 'Blaine County Sheriffs Office - K9')
	AddTextEntry('pol_LIV5', 'San Andreas State Police')
	AddTextEntry('pol_LIV6', 'San Andreas State Police - K9')
	AddTextEntry('pol_LIV7', 'Department of Corrections')
	AddTextEntry('pol_LIV8', 'San Andreas Park Rangers')
	AddTextEntry('pol_LIV9', 'San Andreas Park Rangers - K9')
	AddTextEntry('pol_LIV17', 'BCSO Ghost (HC Only)')
	AddTextEntry('pol_LIV18', 'LSPD Ghost (HC Only)')
	AddTextEntry("POLCHAR_LIV_SASP2", "SASP Snow Leopard HP")
	AddTextEntry('POL_LIV_INT','San Andreas Pursuit Interceptors')
	
	AddTextEntry('POL_ANT1','LSPD City Range')
	AddTextEntry('POL_ANT2','BCSO County Range')
	AddTextEntry('POL_ANT3','SASP State Range')
	AddTextEntry('POL_ANT4','State Range Antenna')
	AddTextEntry('POL_ALPR','ALPR Cameras (PD)')
	AddTextEntry('POL_ALPR2','ALPR Cameras & Aero Package')
	AddTextEntry('POL_SLICK', 'Slicktop')
	AddTextEntry('POL_SLICK2', 'Slicktop')
	AddTextEntry('POL_SLICK3', 'Slicktop')
	AddTextEntry('POL_SLICK4', 'Slicktop')
	AddTextEntry('POL_RAM1', 'LSPD Push Bar')
	AddTextEntry('POL_RAM2', 'BCSO Bullbar')
	AddTextEntry('POL_RAM3', 'SASP/Ranger Wrap-Around Bullbar')
	AddTextEntry('POL_RAM4', 'SASP/Ranger Wrap-Around Bullbar')
	AddTextEntry('pol_DIV','Divider')
	AddTextEntry('pol_DIV2','Divider & Gunrack')
	AddTextEntry('pol_K9','Add Rear Seats/Remove K9 Cage')
	AddTextEntry('pol_CONS','MDW, Radio & Wisen Siren Controller') 
	AddTextEntry('pol_CONSOLE','MDW, Radio & Wisen Siren Controller') 
	AddTextEntry('POL_TRUNK1','Evidence Case')
	AddTextEntry('POL_TRUNK2','Fire Extinguisher')
	AddTextEntry('POL_TRUNK3','Cases & Extinguisher')
	AddTextEntry('pol_RADAR','Dash Radar')
	AddTextEntry('pol_LIGHT','Reading Light')
	AddTextEntry('POL_CAGE','Roll Cage')
	AddTextEntry('POL_CAGE2','Roll Cage & Rifle Rack')
	-- // Charger
	AddTextEntry("POLCHAR_SPL0", "SRT Spoiler (Cpt+)")
	AddTextEntry("POLCHAR_SPL1", "Hellcat Spoiler (SRU Leaders)")
	AddTextEntry("POLCHAR_BBAR_1", "Widebar")
	AddTextEntry("POLCHAR_BBAR_2", "Widebar for Hellcat Conversion (SRU Leaders)")
	AddTextEntry("POL_CHAR_CONVER", "Hellcat Conversion (SRU Leaders)")
	-- // Explorer
	AddTextEntry("POLEXP_ANT1", "LSPD City Range")
	AddTextEntry("POLEXP_ANT2", "State & County Range")
	AddTextEntry("POLEXP_BBAR_1", "Widebar")
	AddTextEntry("POLEXP_ANT1", "LSPD City Range")
	AddTextEntry("POLEXP_ANT2", "State & County Range")
	AddTextEntry("POLEXP_BBAR_1", "Widebar")
	AddTextEntry("FLAG_001", "United States of America")
	AddTextEntry("FLAG_002", "Australia")
	AddTextEntry("FLAG_003", "Brazil")
	AddTextEntry("FLAG_004", "Spain")
	AddTextEntry("FLAG_005", "Canada")
	AddTextEntry("FLAG_006", "United Kingdom")
	AddTextEntry("FLAG_007", "Scotland")
	AddTextEntry("FLAG_008", "Japan")
	AddTextEntry("FLAG_009", "Germany")
	AddTextEntry("FLAG_010", "France")
	AddTextEntry("FLAG_011", "Italy")
	AddTextEntry("FLAG_012", "Switzerland")
	AddTextEntry("FLAG_013", "Jamaica")
	AddTextEntry("FLAG_014", "Colombia")
	AddTextEntry("FLAG_015", "Norway")
	AddTextEntry("FLAG_016", "Russia")
	AddTextEntry("FLAG_017", "South Africa")
	AddTextEntry("FLAG_018", "Mexico")
	AddTextEntry("FLAG_019", "Belgium")
	AddTextEntry("FLAG_020", "Sweden")
	AddTextEntry("FLAG_021", "Argentina")
	AddTextEntry("FLAG_022", "Turkey")
	AddTextEntry("FLAG_023", "Ireland")
	AddTextEntry("FLAG_024", "Wales")
	AddTextEntry("FLAG_025", "England")
	AddTextEntry("STICKER_K9", "K9")
	AddTextEntry("STICKER_202", "A_202")
	AddTextEntry("STICKER_238", "A_238")
	AddTextEntry("STICKER_255", "A_255")
	AddTextEntry("STICKER_331", "A_331")
	AddTextEntry("STICKER_337", "A_337")
	AddTextEntry("STICKER_355", "A_355")
	AddTextEntry("STICKER_397", "A_397")
	AddTextEntry("STICKER_402", "A_402")
	AddTextEntry("STICKER_423", "A_423")
	AddTextEntry("STICKER_455", "A_455")
	AddTextEntry("STICKER_460", "A_460")
	AddTextEntry("STICKER_469", "A_469")
	AddTextEntry("STICKER_485", "A_485")
	AddTextEntry("STICKER_B_215", "B_215")
	AddTextEntry("STICKER_B_270", "B_270")
	AddTextEntry("STICKER_B_319", "B_319")
	AddTextEntry("STICKER_B_385", "B_385")
	AddTextEntry("STICKER_B_431", "B_431")
	AddTextEntry("STICKER_B_447", "B_447")
	AddTextEntry("STICKER_B_451", "B_451")
	AddTextEntry("STICKER_B_484", "B_484")
	AddTextEntry("STICKER_B_490", "B_490")
	AddTextEntry("STICKER_SAPR", "Park Rangers")
end)